name: LineageOS 22.1 Build for L3A
permissions: write-all

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVICE: wade
      BRANCH: lineage-22.1

    steps:
      - name: Machine Information
        run: |
          cd /mnt
          echo "======================="
          lscpu | grep -E "name|Core|Thread"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1
          echo "======================="
          
      - name: Checkout repository
        uses: actions/checkout@main
        
      - name: Set Up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          sudo apt-get install -y openjdk-11-jdk  # JDK for LineageOS 22.1
          sudo apt-get install -y python-is-python3  # Python 3 for LineageOS 22.1
          echo "export USE_CCACHE=1" >> ~/.bashrc
          echo "export CCACHE_EXEC=/usr/bin/ccache" >> ~/.bashrc
          source ~/.bashrc
          ccache -M 25G  # 设置缓存大小为 50GB


      - name: Install the `repo` command
        run: |
          mkdir -p /mnt/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > /mnt/bin/repo
          chmod a+x /mnt/bin/repo

      - name: Initialize LineageOS Source Repository
        run: |
          mkdir -p /mnt/android/lineage
          cd /mnt/android/lineage
          /mnt/bin/repo init -u https://github.com/LineageOS/android.git -b $BRANCH --git-lfs --no-clone-bundle
          /mnt/bin/repo sync

      - name: Prepare Device-Specific Code
        run: |
          cd /mnt/android/lineage
          source build/envsetup.sh
          breakfast $DEVICE
          lunch lineage_$DEVICE-userdebug

      - name: Extract Proprietary Blobs
        run: |
          cd /mnt/android/lineage/device/askey/wade
          ./extract-files.sh  # 或者 ./extract-files.py，根据实际情况选择

      - name: Start the Build
        run: |
          cd /mnt/android/lineage
          croot
          brunch wade
          

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@main
        with:
          name: LineageOS-$DEVICE
          path: /mnt/android/lineage/out/target/product/$DEVICE/
